import {
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  products1,
  products2,
  products3,
  products4,
  products5,
  products6,
  products7,
  products8,
  products9,
  products10,
  products11,
  products12,
  products13,
  products14,
  products15,
  products16,
  products17,
  products18,
  products19,
  products20,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Vase",
    price: "435.00",
    badge: true,
    des: "Elevate your space with our exquisite Clay Flower Vase, a perfect blend of timeless craftsmanship and natural beauty.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Clay vessel",
    price: "149.00",
    badge: false,
    des: "Timeless elegance meets artisanal craftsmanship in our exquisite clay vessel, adding a touch of rustic charm to your space.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Marbel Mortar and pestel",
    price: "199.00",
    badge: true,
    des: "Experience the timeless elegance and culinary precision with our Clay Marble Mortar and Pestle, a stylish kitchen essential for grinding and blending spices effortlessly.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Clay Pot",
    price: "149.00",
    badge: false,
    des: "Exquisite craftsmanship meets timeless elegance in our Clay Pot collection, offering versatile and artfully designed pieces to elevate your culinary experience.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Clay Tea Cups",
    price: "249.00",
    badge: true,
    des: "Artisan-crafted clay tea cups, a perfect blend of elegance and functionality for a truly sensory tea-drinking experience.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Plant Pot",
    price: "199.00",
    badge: true,
    des: "Elevate your greenery with our stylish and durable clay plant pots, blending timeless design with premium craftsmanship for a touch of nature in every space.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Cofee Mugs",
    price: "169.00",
    badge: true,
    des: "Experience the perfect blend of rustic charm and modern elegance with our artisan-crafted clay coffee mugs, combining style and functionality for your daily brew.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Clay Sculpture",
    price: "299.00",
    badge: false,
    des: "Captivating and intricate clay sculptures, each a unique masterpiece, crafted with skill and passion to bring artistic elegance to your space.",
  },
  {
    _id: 1013,
    img: products1,
    productName: "Divine Durga Clay Sculpture",
    price: "359.00",
    badge: false,
    des: "Embrace the divine energy with our meticulously crafted Divine Durga Clay Sculpture, a symbol of strength, grace, and spirituality for your sacred space.",
  },

  {
    _id: 1014,
    img: products2,
    productName: "Buddha Clay Sculpture",
    price: "249.00",
    badge: true,
    des: "Experience serenity and mindfulness embodied in our exquisite Buddha Clay Sculpture, a harmonious blend of artistic craftsmanship and spiritual essence for your home or sacred space.",
  },
  {
    _id: 1015,
    img: products3,
    productName: "White Cup",
    price: "179.00",
    badge: false,
    des: "Elevate your beverage experience with the timeless elegance of our White Cup, a perfect blend of style and simplicity.",
  },
  {
    _id: 1016,
    img: products4,
    productName: "Long Form Clay Vessel",
    price: "299.00",
    badge: true,
    des: "Elevate your living space with our exquisite Long Form Clay Vessel, meticulously crafted to blend timeless design with functional artistry.",
  },
  {
    _id: 1017,
    img: products5,
    productName: "Clay Mini TerraGrow Pot",
    price: "219.00",
    badge: false,
    des: "Experience the joy of nurturing your favorite plants with our Clay Mini TerraGrow Pot, a perfect blend of elegance and functionality for your indoor garden.",
  },
  {
    _id: 1018,
    img: products6,
    productName: "Round Table Clock",
    price: "44.00",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: products7,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: products8,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1028,
    img: products9,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: products10,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: products11,
    productName: "Marbel Mortar and pestel",
    price: "199.00",
    badge: true,
    des: "Experience the timeless elegance and culinary precision with our Clay Marble Mortar and Pestle, a stylish kitchen essential for grinding and blending spices effortlessly.",
  },
  {
    _id: 1031,
    img: products12,
    productName: "Clay Pot",
    price: "149.00",
    badge: false,
    des: "Exquisite craftsmanship meets timeless elegance in our Clay Pot collection, offering versatile and artfully designed pieces to elevate your culinary experience.",
  },
  {
    _id: 1032,
    img: products13,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: products14,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: products15,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: products16,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: products17,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: products18,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: products19,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: products20,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== PaginationItems End here =================
